:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: description
      :label: Description
    - :name: type_of
      :label: Type of creature
    - :name: universe_id
      :label: Universe
:looks:
  :label: Looks
  :icon: pets
  :attributes:
    - :name: color
      :label: Color
    - :name: shape
      :label: Shape
    - :name: size
      :label: Size
    - :name: notable_features
      :label: Notable features
    - :name: materials
      :label: Materials
:traits:
  :label: Traits
  :icon: fingerprint
  :attributes:
    - :name: aggressiveness
      :label: Aggressiveness
    - :name: attack_method
      :label: Method of attack
    - :name: defense_method
      :label: Methods of defense
    - :name: maximum_speed
      :label: Maximum speed
    - :name: strengths
      :label: Strengths
    - :name: weaknesses
      :label: Weaknesses
    - :name: sounds
      :label: Sounds
    - :name: spoils
      :label: Spoils
:habitat:
  :label: Habitat
  :icon: location_on
  :attributes:
    - :name: preferred_habitat
      :label: Preferred habitat
    - :name: habitats
      :label: Habitats
    - :name: food_sources
      :label: Food sources
    - :name: migratory_patterns
      :label: Migratory patterns
    - :name: reproduction
      :label: Reproductive patterns
    - :name: herd_patterns
      :label: Herding patterns
:comparisons:
  :label: Comparisons
  :icon: call_split
  :attributes:
    - :name: similar_animals
      :label: Similar creatures
    - :name: symbolisms
      :label: Symbolisms
    - :name: related_creatures
      :label: Related creatures
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
