:overview:
  :label: Overview
  :icon: info
  :attributes:
    - :name: name
      :label: Name
    - :name: other_names
      :label: Other names
    - :name: universe_id
      :label: Universe
:info:
  :label: Info
  :icon: forum
  :attributes:
    - :name: history
      :label: History
    - :name: typology
      :label: Typology
    - :name: dialectical_information
      :label: Dialectical information
    - :name: register
      :label: Register
:phonology:
  :label: Phonology
  :icon: speaker_notes
  :attributes:
    - :name: phonology
      :label: Phonology
:grammar:
  :label: Grammar
  :icon: list
  :attributes:
    - :name: grammar
      :label: Grammar
:entities:
  :label: Entities
  :icon: settings_input_component
  :attributes:
    - :name: numbers
      :label: Numbers
    - :name: quantifiers
      :label: Quantifiers
:gallery:
  :label: Gallery
  :icon: photo_library
:changelog:
  :label: Changelog
  :icon: history
:notes:
  :label: Notes
  :icon: edit
  :attributes:
    - :name: notes
      :label: Notes
    - :name: private_notes
      :label: Private notes
      :description: Private notes are <em>always</em> visible to only you, even if content is made public and shared.
